title: "The Endo Initiative"
description: "Parent company for all endeavors of Endo."
url: "https://endoinitiative.com"
baseurl: ""  # always empty for custom domains unless you publish to a subfolder
markdown: kramdown
theme: null

favicon-32x32: "favicon-32.png"
apple-touch-icon-180x180-precomposed: "apple-touch-icon.png"
msapplication_tileimage: "mstile-150x150.png"
msapplication_tilecolor: "#ffffff"
